#!/bin/bash
# Runs gazebo with the correct plugin path
#WORLD=viewer.world
WORLD=view-evolved.world
CMD=gazebo
GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:`pwd`/../build GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:`pwd`/../../revolve/tools/models:`pwd`/models $CMD -u $WORLD
